# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/faeqh/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-1908-Faeq/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.cache/wt} [current_project]
set_property parent.project_path {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/fib_prog.mem}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/sum_n.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/alu.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/alu_decoder.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/branch_comp.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/clk_dvd.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/control_unit.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/data_file.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/extension.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/instr_decoder.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/instr_file.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/mux.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/pc.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/pc_adder.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/reg_file.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/sign_extend.v}
  {C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/sources_1/new/top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/constrs_1/new/CONSTRAINT.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/faeqh/Documents/Vivado projects/RISC_V_Pipeline/RISC_V_Pipeline.srcs/constrs_1/new/CONSTRAINT.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
